OPTION CASEMAP:NONE
EXTERN GetOriginalAGSProcByName:PROC

; Preserve integer and floating-point arguments and leave stack arguments in
; their original positions. Each aligned target slot is cached atomically.
FORWARD_AGS MACRO procName, nameLabel, targetLabel
    LOCAL resolved
    .code
    PUBLIC procName
procName PROC FRAME
    sub rsp, 0A8h
    .allocstack 0A8h
    .endprolog
    mov rax, targetLabel
    test rax, rax
    jnz resolved
    mov [rsp+20h], rcx
    mov [rsp+28h], rdx
    mov [rsp+30h], r8
    mov [rsp+38h], r9
    movaps [rsp+40h], xmm0
    movaps [rsp+50h], xmm1
    movaps [rsp+60h], xmm2
    movaps [rsp+70h], xmm3
    lea rcx, nameLabel
    call GetOriginalAGSProcByName
    mov targetLabel, rax
    mov rcx, [rsp+20h]
    mov rdx, [rsp+28h]
    mov r8, [rsp+30h]
    mov r9, [rsp+38h]
    movaps xmm0, [rsp+40h]
    movaps xmm1, [rsp+50h]
    movaps xmm2, [rsp+60h]
    movaps xmm3, [rsp+70h]
resolved:
    add rsp, 0A8h
    jmp rax
procName ENDP
ENDM

.const
agsCheckDriverVersion_name BYTE "agsCheckDriverVersion", 0
agsDeInitialize_name BYTE "agsDeInitialize", 0
agsDriverExtensionsDX11_BeginUAVOverlap_name BYTE "agsDriverExtensionsDX11_BeginUAVOverlap", 0
agsDriverExtensionsDX11_CreateBuffer_name BYTE "agsDriverExtensionsDX11_CreateBuffer", 0
agsDriverExtensionsDX11_CreateDevice_name BYTE "agsDriverExtensionsDX11_CreateDevice", 0
agsDriverExtensionsDX11_CreateTexture1D_name BYTE "agsDriverExtensionsDX11_CreateTexture1D", 0
agsDriverExtensionsDX11_CreateTexture2D_name BYTE "agsDriverExtensionsDX11_CreateTexture2D", 0
agsDriverExtensionsDX11_CreateTexture3D_name BYTE "agsDriverExtensionsDX11_CreateTexture3D", 0
agsDriverExtensionsDX11_DestroyDevice_name BYTE "agsDriverExtensionsDX11_DestroyDevice", 0
agsDriverExtensionsDX11_EndUAVOverlap_name BYTE "agsDriverExtensionsDX11_EndUAVOverlap", 0
agsDriverExtensionsDX11_GetMaxClipRects_name BYTE "agsDriverExtensionsDX11_GetMaxClipRects", 0
agsDriverExtensionsDX11_IASetPrimitiveTopology_name BYTE "agsDriverExtensionsDX11_IASetPrimitiveTopology", 0
agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirect_name BYTE "agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirect", 0
agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirectCountIndirect_name BYTE "agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirectCountIndirect", 0
agsDriverExtensionsDX11_MultiDrawInstancedIndirect_name BYTE "agsDriverExtensionsDX11_MultiDrawInstancedIndirect", 0
agsDriverExtensionsDX11_MultiDrawInstancedIndirectCountIndirect_name BYTE "agsDriverExtensionsDX11_MultiDrawInstancedIndirectCountIndirect", 0
agsDriverExtensionsDX11_NotifyResourceBeginAllAccess_name BYTE "agsDriverExtensionsDX11_NotifyResourceBeginAllAccess", 0
agsDriverExtensionsDX11_NotifyResourceEndAllAccess_name BYTE "agsDriverExtensionsDX11_NotifyResourceEndAllAccess", 0
agsDriverExtensionsDX11_NotifyResourceEndWrites_name BYTE "agsDriverExtensionsDX11_NotifyResourceEndWrites", 0
agsDriverExtensionsDX11_NumPendingAsyncCompileJobs_name BYTE "agsDriverExtensionsDX11_NumPendingAsyncCompileJobs", 0
agsDriverExtensionsDX11_SetClipRects_name BYTE "agsDriverExtensionsDX11_SetClipRects", 0
agsDriverExtensionsDX11_SetDepthBounds_name BYTE "agsDriverExtensionsDX11_SetDepthBounds", 0
agsDriverExtensionsDX11_SetDiskShaderCacheEnabled_name BYTE "agsDriverExtensionsDX11_SetDiskShaderCacheEnabled", 0
agsDriverExtensionsDX11_SetMaxAsyncCompileThreadCount_name BYTE "agsDriverExtensionsDX11_SetMaxAsyncCompileThreadCount", 0
agsDriverExtensionsDX11_SetViewBroadcastMasks_name BYTE "agsDriverExtensionsDX11_SetViewBroadcastMasks", 0
agsDriverExtensionsDX11_WriteBreadcrumb_name BYTE "agsDriverExtensionsDX11_WriteBreadcrumb", 0
agsDriverExtensionsDX12_CreateDevice_name BYTE "agsDriverExtensionsDX12_CreateDevice", 0
agsDriverExtensionsDX12_CreateFromDevice_name BYTE "agsDriverExtensionsDX12_CreateFromDevice", 0
agsDriverExtensionsDX12_Destroy_name BYTE "agsDriverExtensionsDX12_Destroy", 0
agsDriverExtensionsDX12_DestroyDevice_name BYTE "agsDriverExtensionsDX12_DestroyDevice", 0
agsDriverExtensionsDX12_PopMarker_name BYTE "agsDriverExtensionsDX12_PopMarker", 0
agsDriverExtensionsDX12_PushMarker_name BYTE "agsDriverExtensionsDX12_PushMarker", 0
agsDriverExtensionsDX12_SetMarker_name BYTE "agsDriverExtensionsDX12_SetMarker", 0
agsGetVersionNumber_name BYTE "agsGetVersionNumber", 0
agsSetDisplayMode_name BYTE "agsSetDisplayMode", 0

.data
ALIGN 8
agsCheckDriverVersion_target QWORD 0
ALIGN 8
agsDeInitialize_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_BeginUAVOverlap_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_CreateBuffer_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_CreateDevice_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_CreateTexture1D_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_CreateTexture2D_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_CreateTexture3D_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_DestroyDevice_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_EndUAVOverlap_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_GetMaxClipRects_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_IASetPrimitiveTopology_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirect_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirectCountIndirect_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_MultiDrawInstancedIndirect_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_MultiDrawInstancedIndirectCountIndirect_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_NotifyResourceBeginAllAccess_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_NotifyResourceEndAllAccess_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_NotifyResourceEndWrites_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_NumPendingAsyncCompileJobs_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_SetClipRects_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_SetDepthBounds_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_SetDiskShaderCacheEnabled_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_SetMaxAsyncCompileThreadCount_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_SetViewBroadcastMasks_target QWORD 0
ALIGN 8
agsDriverExtensionsDX11_WriteBreadcrumb_target QWORD 0
ALIGN 8
agsDriverExtensionsDX12_CreateDevice_target QWORD 0
ALIGN 8
agsDriverExtensionsDX12_CreateFromDevice_target QWORD 0
ALIGN 8
agsDriverExtensionsDX12_Destroy_target QWORD 0
ALIGN 8
agsDriverExtensionsDX12_DestroyDevice_target QWORD 0
ALIGN 8
agsDriverExtensionsDX12_PopMarker_target QWORD 0
ALIGN 8
agsDriverExtensionsDX12_PushMarker_target QWORD 0
ALIGN 8
agsDriverExtensionsDX12_SetMarker_target QWORD 0
ALIGN 8
agsGetVersionNumber_target QWORD 0
ALIGN 8
agsSetDisplayMode_target QWORD 0

.code
FORWARD_AGS agsCheckDriverVersion, agsCheckDriverVersion_name, agsCheckDriverVersion_target
FORWARD_AGS agsDeInitialize, agsDeInitialize_name, agsDeInitialize_target
FORWARD_AGS agsDriverExtensionsDX11_BeginUAVOverlap, agsDriverExtensionsDX11_BeginUAVOverlap_name, agsDriverExtensionsDX11_BeginUAVOverlap_target
FORWARD_AGS agsDriverExtensionsDX11_CreateBuffer, agsDriverExtensionsDX11_CreateBuffer_name, agsDriverExtensionsDX11_CreateBuffer_target
FORWARD_AGS agsDriverExtensionsDX11_CreateDevice, agsDriverExtensionsDX11_CreateDevice_name, agsDriverExtensionsDX11_CreateDevice_target
FORWARD_AGS agsDriverExtensionsDX11_CreateTexture1D, agsDriverExtensionsDX11_CreateTexture1D_name, agsDriverExtensionsDX11_CreateTexture1D_target
FORWARD_AGS agsDriverExtensionsDX11_CreateTexture2D, agsDriverExtensionsDX11_CreateTexture2D_name, agsDriverExtensionsDX11_CreateTexture2D_target
FORWARD_AGS agsDriverExtensionsDX11_CreateTexture3D, agsDriverExtensionsDX11_CreateTexture3D_name, agsDriverExtensionsDX11_CreateTexture3D_target
FORWARD_AGS agsDriverExtensionsDX11_DestroyDevice, agsDriverExtensionsDX11_DestroyDevice_name, agsDriverExtensionsDX11_DestroyDevice_target
FORWARD_AGS agsDriverExtensionsDX11_EndUAVOverlap, agsDriverExtensionsDX11_EndUAVOverlap_name, agsDriverExtensionsDX11_EndUAVOverlap_target
FORWARD_AGS agsDriverExtensionsDX11_GetMaxClipRects, agsDriverExtensionsDX11_GetMaxClipRects_name, agsDriverExtensionsDX11_GetMaxClipRects_target
FORWARD_AGS agsDriverExtensionsDX11_IASetPrimitiveTopology, agsDriverExtensionsDX11_IASetPrimitiveTopology_name, agsDriverExtensionsDX11_IASetPrimitiveTopology_target
FORWARD_AGS agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirect, agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirect_name, agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirect_target
FORWARD_AGS agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirectCountIndirect, agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirectCountIndirect_name, agsDriverExtensionsDX11_MultiDrawIndexedInstancedIndirectCountIndirect_target
FORWARD_AGS agsDriverExtensionsDX11_MultiDrawInstancedIndirect, agsDriverExtensionsDX11_MultiDrawInstancedIndirect_name, agsDriverExtensionsDX11_MultiDrawInstancedIndirect_target
FORWARD_AGS agsDriverExtensionsDX11_MultiDrawInstancedIndirectCountIndirect, agsDriverExtensionsDX11_MultiDrawInstancedIndirectCountIndirect_name, agsDriverExtensionsDX11_MultiDrawInstancedIndirectCountIndirect_target
FORWARD_AGS agsDriverExtensionsDX11_NotifyResourceBeginAllAccess, agsDriverExtensionsDX11_NotifyResourceBeginAllAccess_name, agsDriverExtensionsDX11_NotifyResourceBeginAllAccess_target
FORWARD_AGS agsDriverExtensionsDX11_NotifyResourceEndAllAccess, agsDriverExtensionsDX11_NotifyResourceEndAllAccess_name, agsDriverExtensionsDX11_NotifyResourceEndAllAccess_target
FORWARD_AGS agsDriverExtensionsDX11_NotifyResourceEndWrites, agsDriverExtensionsDX11_NotifyResourceEndWrites_name, agsDriverExtensionsDX11_NotifyResourceEndWrites_target
FORWARD_AGS agsDriverExtensionsDX11_NumPendingAsyncCompileJobs, agsDriverExtensionsDX11_NumPendingAsyncCompileJobs_name, agsDriverExtensionsDX11_NumPendingAsyncCompileJobs_target
FORWARD_AGS agsDriverExtensionsDX11_SetClipRects, agsDriverExtensionsDX11_SetClipRects_name, agsDriverExtensionsDX11_SetClipRects_target
FORWARD_AGS agsDriverExtensionsDX11_SetDepthBounds, agsDriverExtensionsDX11_SetDepthBounds_name, agsDriverExtensionsDX11_SetDepthBounds_target
FORWARD_AGS agsDriverExtensionsDX11_SetDiskShaderCacheEnabled, agsDriverExtensionsDX11_SetDiskShaderCacheEnabled_name, agsDriverExtensionsDX11_SetDiskShaderCacheEnabled_target
FORWARD_AGS agsDriverExtensionsDX11_SetMaxAsyncCompileThreadCount, agsDriverExtensionsDX11_SetMaxAsyncCompileThreadCount_name, agsDriverExtensionsDX11_SetMaxAsyncCompileThreadCount_target
FORWARD_AGS agsDriverExtensionsDX11_SetViewBroadcastMasks, agsDriverExtensionsDX11_SetViewBroadcastMasks_name, agsDriverExtensionsDX11_SetViewBroadcastMasks_target
FORWARD_AGS agsDriverExtensionsDX11_WriteBreadcrumb, agsDriverExtensionsDX11_WriteBreadcrumb_name, agsDriverExtensionsDX11_WriteBreadcrumb_target
FORWARD_AGS agsDriverExtensionsDX12_CreateDevice, agsDriverExtensionsDX12_CreateDevice_name, agsDriverExtensionsDX12_CreateDevice_target
FORWARD_AGS agsDriverExtensionsDX12_CreateFromDevice, agsDriverExtensionsDX12_CreateFromDevice_name, agsDriverExtensionsDX12_CreateFromDevice_target
FORWARD_AGS agsDriverExtensionsDX12_Destroy, agsDriverExtensionsDX12_Destroy_name, agsDriverExtensionsDX12_Destroy_target
FORWARD_AGS agsDriverExtensionsDX12_DestroyDevice, agsDriverExtensionsDX12_DestroyDevice_name, agsDriverExtensionsDX12_DestroyDevice_target
FORWARD_AGS agsDriverExtensionsDX12_PopMarker, agsDriverExtensionsDX12_PopMarker_name, agsDriverExtensionsDX12_PopMarker_target
FORWARD_AGS agsDriverExtensionsDX12_PushMarker, agsDriverExtensionsDX12_PushMarker_name, agsDriverExtensionsDX12_PushMarker_target
FORWARD_AGS agsDriverExtensionsDX12_SetMarker, agsDriverExtensionsDX12_SetMarker_name, agsDriverExtensionsDX12_SetMarker_target
FORWARD_AGS agsGetVersionNumber, agsGetVersionNumber_name, agsGetVersionNumber_target
FORWARD_AGS agsSetDisplayMode, agsSetDisplayMode_name, agsSetDisplayMode_target

END
